/// Updated at 04/01/2018 08:51:50
Class Users.Collector Extends (%RegisteredObject, Form.Adaptor)
{

/*
Parameter FORMNAME = "Collector";

Parameter OBJPERMISSIONS As %String = "CRUD";

Parameter DISPLAYPROPERTY As %String = "Username";

Parameter FORMORDERBY As %String = "Username";

Property Username As %String [ Required ];

Property Name As %String [ Required ];

Property Surname As %String [ Required ];

Property Patronymic As %String;

Property Password As %String;

Property Roles As %String;

Property Id As %String;
*/
}
